#15 and #4 is addressed here
JuliaSmoothOptimizers/FluxNLPModels.jl pull request #25
Opened 2023-10-31 22:21 UTC by farhadrclass

I had also updated the Flux and therefore some updates are due to that

2023-10-31 22:22 UTC, farhadrclass commented
@dpo,  @d-monnet   and @tmigot  to review?

2023-10-31 22:24 UTC, farhadrclass commented
It will error out since we needed to use Julia 1.9 for Flux 
I believe we need to update the CI ?

2023-11-01 09:46 UTC, tmigot requested changes
Hi @farhadrclass ! Thank you for the PR.
I would strongly recommend to open focused PR, in other words, more PRs but each with a simple focus. This way it is easier to review and approve :).
A start would be to open a first PR to update to Julia 1.9. Can you also explain a bit further why we drop 1.6?

2023-11-01 09:46 UTC, tmigot commented on Project.toml
> +CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
```suggestion
```

2023-11-01 22:25 UTC, farhadrclass commented
Hi @tmigot 

 Thank you for the review.

The reason for combining the 4 and 15 bugs are that they are the same thing, one is asking to have unit test for different precision and the other one is mentioning that Float16 is not supported.


The reason we needed Julia 1.9+ is that we need Flux 13 and or 14th since they added support for changing parameters type on the run time and they require Julia 1.9 (Also Float16 is hardware supported :) )


Lastly I had a question on how to fix the errors we are getting for CI and Documentation ?

2023-11-02 09:18 UTC, tmigot commented
> Hi @tmigot
> 
> Thank you for the review.
> 
> The reason for combining the 4 and 15 bugs are that they are the same thing, one is asking to have unit test for different precision and the other one is mentioning that Float16 is not supported.
> 
> The reason we needed Julia 1.9+ is that we need Flux 13 and or 14th since they added support for changing parameters type on the run time and they require Julia 1.9 (Also Float16 is hardware supported :) )
> 
> Lastly I had a question on how to fix the errors we are getting for CI and Documentation ?

Thanks for the additional explanations.
Still, I think you should first open a PR to drop Julia 1.6 (in the Project.toml and in all the config files) that will fix the CI thing.

2023-11-02 09:22 UTC, tmigot commented
The documentation fails because you drop support of Flux 0.13 while it is the version used for the doc https://github.com/JuliaSmoothOptimizers/FluxNLPModels.jl/blob/main/docs/Project.toml

2023-11-03 00:16 UTC, farhadrclass commented
@tmigot  I added a new PR #26 for Julia and flux update, once that resolve, I would rebase this

2023-11-03 14:28 UTC, farhadrclass commented
@tmigot I rebased it and now waiting for it to run the CI

Let me know if anything 
Also some notes on Zygote: due to some reason we need Zygote 0.6.6 since Flux is not using the most updated Zygote

2023-11-07 09:39 UTC, tmigot requested changes
Thanks @farhadrclass for the PR! I made a couple of comments.
Also, Please use git squash to maintain a clean history of commits in your branch.

2023-11-07 09:39 UTC, tmigot commented on test/runtests.jl
> +  # println(norm(grad_x1 - grad_x1_2))
```suggestion
```

2023-11-07 09:39 UTC, tmigot commented on src/utils.jl
> +Sets the vaiables and rebuild the chain to a sepecific type defined by weigths
```suggestion
Sets the variables and rebuild the chain to a specific type defined by weigths.
```

2023-11-07 09:39 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +Evaluate `f(w)`, the objective function of `nlp` at `w`. if `w` and `nlp` precision different, we advance to match the the type of `w`
```suggestion
Evaluate `f(w)`, the objective function of `nlp` at `w`. if `w` and `nlp` precision different, we match the type of `w`
```

2023-11-07 09:39 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +- `w::AbstractVector{V}`: is the vector of weights/variables. The reason for V here is to allow different precision type for weight and models
```suggestion
- `w::AbstractVector{V}`: is the vector of weights/variables. The reason for `V` here is to allow different precision type for weight and models 
```

2023-11-07 09:39 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +  eltype(nlp.w) == V || update_type!(nlp, w) #Check if the type has changed
Would it be possible to use multiple dispatch instead of the if-else on type hère?

2023-11-07 09:39 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +  if (eltype(nlp.w) != V)  # we check if the types are the same,
Would it be possible to use multiple dispatch instead of the if-else on type hère?

2023-11-07 09:39 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +  if (eltype(nlp.w) != V)  # we check if the types are the same,
Would it be possible to use multiple dispatch instead of the if-else on type hère?

2023-11-07 09:39 UTC, tmigot commented on src/utils.jl
> +  if V == Float16
Would it be possible to use multiple dispatch instead of the if-else on type hère?

2023-11-07 09:39 UTC, tmigot commented on Project.toml
> +version = "0.2.0"
This should be done in a separate PR.

2023-11-07 09:39 UTC, tmigot commented on example/MNIST_cnn.jl
> +    Dense(84 => 10),#TODO add softmax
```suggestion
    Dense(84 => 10),
```
I would suggest creating issues for new features instead of todos

2023-11-07 09:39 UTC, tmigot commented on src/FluxNLPModels.jl
> +  loss_f::F = Flux.crossentropy,#Flux.mse, #
What is the motivation for this ? It seems unrelated to this PR.

2023-11-08 23:09 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +  eltype(nlp.w) == V || update_type!(nlp, w) #Check if the type has changed
Let me test it, but the nice thing about here is that when type changes it would be able to handle it still

2023-11-08 23:09 UTC, farhadrclass commented on Project.toml
> +version = "0.2.0"
oh I see, so I keep 1?

2023-11-08 23:10 UTC, farhadrclass commented on src/FluxNLPModels.jl
> +  loss_f::F = Flux.crossentropy,#Flux.mse, #
you are right, I will make a new pr for it

2023-11-14 15:28 UTC, farhadrclass commented on src/utils.jl
> +  if V == Float16
yes

2023-11-14 15:28 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +  eltype(nlp.w) == V || update_type!(nlp, w) #Check if the type has changed
Here I am not sure how since we do not have access to nlp.w type before the call or in the signature of the function

2023-11-14 15:28 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +  if (eltype(nlp.w) != V)  # we check if the types are the same,
same as before

2023-11-14 15:28 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +  eltype(nlp.w) == V || update_type!(nlp, w) #Check if the type has changed
@tmigot  any suggestions on this ?

2023-11-14 15:57 UTC, farhadrclass commented
@tmigot I added some multiple dispatch but not sure about all of them, what do you think

2023-11-17 14:52 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +  if (eltype(nlp.w) != V)  # we check if the types are the same,
In other words, you should have two methods:
````
grad!(nlp::AbstractFluxNLPModel{T, S}, w::AbstractVector{T}, g::AbstractVector{T})
grad!(nlp::AbstractFluxNLPModel{T, S}, w::AbstractVector{V}, g::AbstractVector{V})
```
where in the first one you have `eltype(nlp.w) == V` and therefore in the second one `eltype(nlp.w) != V`.

2023-11-17 14:52 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +Evaluate `f(w)`, the objective function of `nlp` at `w`. if `w` and `nlp` precision different, we match the type of `w`
Please review english here

2023-11-17 14:52 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +- `w::AbstractVector{V}`: is the vector of weights/variables. The reason for `V` here is to allow different precision type for weight and models
Please review english here

2023-11-17 14:53 UTC, tmigot commented on src/utils.jl
> +function update_type(chain::Chain, ::Type)
Need to add this in the tests too.

2023-11-17 14:54 UTC, tmigot commented on src/FluxNLPModels_methods.jl
> +function NLPModels.obj(nlp::AbstractFluxNLPModel{T, S}, w::AbstractVector{V}) where {T, S, V}
See comment on `grad!`

2023-11-17 18:32 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +Evaluate `f(w)`, the objective function of `nlp` at `w`. if `w` and `nlp` precision different, we match the type of `w`
I added print statment: 
```julia
unction NLPModels.obj(nlp::AbstractFluxNLPModel{T, S}, w::AbstractVector{V}) where {T, S, V}
  x, y = nlp.current_training_minibatch
  print("type V is ", V, "\n")
  print("type eltype(nlp.w) is ", eltype(nlp.w), "\n")
  print("type of T is ", T, "\n")
  print("type of eltype(x) is ", eltype(x), "\n")
  print("====================\n")
  eltype(nlp.w) == V || update_type!(nlp, w) #Check if the type has changed 
  if eltype(x) != V
    x = V.(x)
  end

  set_vars!(nlp, w)
  increment!(nlp, :neval_obj)
  return nlp.loss_f(nlp.chain(x), y)
end

```
Then I write a simple test code:
```julia
@testset "Multiple precision test" begin
  # Create test and train dataloaders
  train_data, test_data = getdata(args)

  # Construct model in Float32
  DN = build_model() |> device
  nlp = FluxNLPModel(DN, train_data, test_data)

  x1 = copy(nlp.w)
  obj_x1 = obj(nlp, x1)
  grad_x1 = NLPModels.grad(nlp, x1)

  # change to Float16 
  x2 = Float16.(x1)
  obj_x2 = obj(nlp, x2)
 
  # change to Float32 again, this is where the issue is
  # nlp.w is float16, but T and V both 32 
  obj_x3 = obj(nlp, x1) # x1 is float32, but nlp.w is float16 and nlp{T,S} is float32
end

```
Here is the output :
```julia-repl
type V is Float32
type eltype(nlp.w) is Float32
type of T is Float32
type of eltype(x) is Float32
====================
type V is Float16
type eltype(nlp.w) is Float32
type of T is Float32
type of eltype(x) is Float32
update_type!
type eltype(nlp.w) is after type change Float16
====================
type V is Float32
type eltype(nlp.w) is Float16
type of T is Float32
type of eltype(x) is Float32
```

 the eltype(nlp.w) is float16 but T and V both are Float32,   

# change to Float32 again, this is where the issue is
  nlp.w is float16, but T and V both 32 
  obj_x3 = obj(nlp, x1) # x1 is float32, but nlp.w is float16 and nlp{T,S} is float32

2023-11-17 18:33 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +Evaluate `f(w)`, the objective function of `nlp` at `w`. if `w` and `nlp` precision different, we match the type of `w`
so the multiple dispatch would not handel this `

2023-11-23 18:12 UTC, farhadrclass commented on src/FluxNLPModels_methods.jl
> +function NLPModels.obj(nlp::AbstractFluxNLPModel{T, S}, w::AbstractVector{V}) where {T, S, V}
Commented before on grad!

2023-11-23 18:35 UTC, farhadrclass commented
@tmigot  I added your suggestions, except the multip-dispatch which I explained.
Once this is good to go we can start the other prs

2023-11-23 18:51 UTC, tmigot commented on Project.toml
> +version = "0.2.0"
Yes, you keep the 1

2023-11-23 18:52 UTC, tmigot commented on test/runtests.jl
> +  # println(norm(grad_x1 - grad_x1_2))
A commented print  does not seem appropriate

2023-11-23 18:55 UTC, farhadrclass commented on test/runtests.jl
> +  # println(norm(grad_x1 - grad_x1_2))
agreed

2023-11-23 18:56 UTC, farhadrclass commented on Project.toml
> +version = "0.2.0"
should I make a PR for this ?

2023-11-23 21:23 UTC, merged

2023-11-25 03:49 UTC, tmigot commented
@farhadrclass please use ''squash and merge'' button so that we try to keep a clean history of commit (hère 18commits have been merged while it is only a small change)

2023-11-25 03:52 UTC, farhadrclass commented
do you want me to do it now or in the future PR?

2023-11-25 03:57 UTC, farhadrclass commented
I do not know how to do it after you merge btw @tmigot

2023-12-16 17:13 UTC, tmigot commented
> I do not know how to do it after you merge btw @tmigot

This is done :). It is better to "squash and merge" to keep a clean history